### ISSUE TITLE
Feature Request: Support custom LogFormats (Apache)

### ISSUE THREAD

**Issue by sudofox** [Songmu/axslogparser#15]
I have a custom LogFormat, which is used to tell a few things:

a) whether the request was received directly, or if it came via our Varnish 
b) The real visitor IP address (via a `Varnish-Client-IP` header)

```
LogFormat "%{Varnish-Client-IP}i via %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
```

There should be a way to optionally specify the LogFormat so that it can deal with access logs with slightly different format as a result. At the moment, it only deals with the number of requests and the breakdown by response code, so it should be alright to just toss out the non-relevant fields.

(This would also mean an optional extra config option could be passed for mackerel-plugin-accesslog)

**Comment by Songmu** [comment]
Thanks for the issue. However, I think this is not the scope of this library, so I'll close it.
