### ISSUE TITLE
Making req parsing more robust?

### ISSUE THREAD

**Issue by motemen** [Songmu/axslogparser#17]
Especially when you are using nginx, there may be cases that the `req` field is blank or malformed as an HTTP request line.

You can reproduce such access log by for example setting nginx's log format to `req:$request` and sending an empty request:

~~~
echo | nc nginx-server 80
~~~

So, empty `req` being valid in access log (though not a valid HTTP request), I think axslogparser should not fail to parse such log line. Currently it fails because of `breakdownRequest`. What do you think regarding changing this behaviour?

**Comment by Songmu** [comment]
I see.

It is invalid HTTP Request, but  there are various HTTP Requests in the natural world, so it's bothering how to handle them.

**Comment by Songmu** [comment]
In my opinion, this should be an error, but I think it would be better to be able to handle it.

Apart from that, it may be possible to provide an option like looseCheck.

**Comment by motemen** [comment]
I have just created a [PR](https://github.com/Songmu/axslogparser/pull/18) that adds Loose option to parsers. Please take a look, thanks!

**Comment by Songmu** [comment]
Merged #18 and released as v1.2.0.
